name = "Countdown Timer"

uid = "2d6e9a3f-aa62-633c-0ce3-390dc16527cea09b75b2"

type = "theme"

[theme]
name = "Countdown Timer"
target = "section"

[[blocks]]
target = "section"
name = "Countdown Widget"
type = "timer"